import json
import logging
import markdown2

from odoo import _, api, fields, models
from odoo.exceptions import MissingError, UserError, ValidationError

from odoo.addons.llm_mail_message_subtypes.const import (
    LLM_TOOL_RESULT_SUBTYPE_XMLID,
)

_logger = logging.getLogger(__name__)

class MailMessage(models.Model):
    _inherit = "mail.message"

    user_vote = fields.Integer(
        string="User Vote",
        default=0,
        help="Vote status given by the user. 0: No vote, 1: Upvoted, -1: Downvoted.",
    )

    generation_inputs = fields.Text(
        string="Media Generation Inputs",
        readonly=True,
        copy=False,
        help="JSON string of inputs used for media generation, if this message initiated such a request."
    )

    @api.constrains("tool_call_id", "subtype_id")
    def _check_tool_message_integrity(self):
        for record in self:
            if record.tool_call_id and record.subtype_id:
                tool_message_subtype = self.env.ref(LLM_TOOL_RESULT_SUBTYPE_XMLID)
                if record.subtype_id.id != tool_message_subtype.id:
                    raise ValidationError(
                        "Tool Call ID can only be set for Tool Messages."
                    )

    def _get_llm_message_format_fields(self):
        """Extend the list of fields fetched by the base message_format."""
        fields_list = super()._get_llm_message_format_fields()
        fields_list.extend(
            [
                "tool_calls",
                "tool_call_id",
                "tool_call_definition",
                "tool_call_result",
                "user_vote",
            ]
        )
        return fields_list

    def set_user_vote(self, message_id, vote_value):  # Add message_id argument
        """
        Finds a message by ID and sets the user vote, performing validation checks.
        Raises MissingError, ValidationError, or UserError if checks fail.
        """
        message = self.env["mail.message"].browse(message_id)
        if not message.exists():
            raise MissingError(
                _("Message with ID %s not found.") % message_id
            )  # Raise error if not found

        if not isinstance(vote_value, int) or vote_value not in [-1, 0, 1]:
            raise ValidationError(
                _(
                    "Invalid vote value. Must be an integer: 1 (up), -1 (down), or 0 (none)."
                )
            )

        if message.is_llm_assistant_message() or message.is_llm_tool_result_message():
            message.sudo().write({"user_vote": vote_value})
            return vote_value
        else:
            raise UserError(
                _("Voting is only allowed on messages generated by the assistant")
            )

    @api.model
    def create_message_from_stream(
        self, thread, stream, subtype_xmlid, placeholder_text="…"
    ):
        """
        thread: the llm.thread record
        stream: iterator of provider chunks (content/tool_calls/error)
        subtype_xmlid: assistant vs tool result XMLID

        Yields UI events, and finally returns the full message record.
        """
        msg = None
        acc, calls = "", []

        for chunk in stream:
            if msg is None and (chunk.get("content") or chunk.get("tool_calls")):
                msg = thread._post_message(
                    subtype_xmlid=subtype_xmlid,
                    body=placeholder_text,
                    author_id=False,
                )
                yield {"type": "message_create", "message": msg.message_format()[0]}

            if chunk.get("content"):
                acc += chunk["content"]
                msg.write({"body": markdown2.markdown(acc)})
                yield {"type": "message_chunk", "message": msg.message_format()[0]}

            if chunk.get("tool_calls"):
                valid = [
                    c
                    for c in chunk["tool_calls"]
                    if isinstance(c, dict) and c.get("id")
                ]
                calls.extend(valid)
                msg.write({"tool_calls": json.dumps(calls)})
                yield {"type": "message_update", "message": msg.message_format()[0]}

            if chunk.get("error"):
                yield {"type": "error", "error": chunk["error"]}
                return

        # final write & update
        msg.write(
            {
                **({"body": markdown2.markdown(acc)} if acc else {}),
                **({"tool_calls": json.dumps(calls)} if calls else {}),
            }
        )
        yield {"type": "message_update", "message": msg.message_format()[0]}
        return msg

    @api.model
    def stream_llm_tool_result(self, thread, tool_call_def):
        """
        Stream a single tool call:
         1) create a placeholder tool‐result message,
         2) yield the "message_create",
         3) execute the tool,
         4) write the result & yield a "message_update",
         5) return the final message record.
        """
        call_id = tool_call_def.get("id")
        fn = tool_call_def.get("function", {})
        name = fn.get("name", "unknown_tool")
        args = fn.get("arguments")

        # 1) placeholder
        msg = thread._post_message(
            subtype_xmlid=LLM_TOOL_RESULT_SUBTYPE_XMLID,
            tool_call_id=call_id,
            tool_call_definition=json.dumps(tool_call_def),
            tool_call_result=None,
            body=f"Executing: {name}…",
            author_id=False,
            tool_name=name,
        )
        yield {"type": "message_create", "message": msg.message_format()[0]}

        # 2) execute + update
        try:
            # to isolate tool call, otherwise transaction error can cause the transaction to fail
            # and the transaction will be rolled back(aborted state)
            with self.env.cr.savepoint():
                result = thread._execute_tool(name, args)
                if not result:
                    raise UserError(f"No result returned from tool '{name}'")
                body = f"Result for {name}"
                write_vals = {"tool_call_result": json.dumps(result), "body": body}
        except Exception as e:
            write_vals = {
                "tool_call_result": json.dumps({"error": str(e)}),
                "body": f"Error executing {name}",
            }
        msg.write(write_vals)
        yield {"type": "message_update", "message": msg.message_format()[0]}

        return msg


    def is_llm_user_media_gen_message(self):
        if self.is_llm_user_message():
            _logger.info(f"is_llm_user_media_gen_message: {self.generation_inputs}")
            result = bool(self.generation_inputs)
            _logger.info(f"is_llm_user_media_gen_message: {result}")
            return result
        return False

    @api.model
    def create_message_from_media_gen_stream(
        self, thread, stream, subtype_xmlid, placeholder_text="Generated media:"
    ):
        """
        thread: the llm.thread record
        stream: iterator of provider media gen method response
        subtype_xmlid: assistant vs tool result XMLID

        Yields UI events, and finally returns the full message record.
        """
        msg = None

        for chunk in stream:
            if msg is None and chunk.get("content"):
                generated_medias = thread.model_id.format_generation_response(
                    chunk["content"],
                )
                attachment_ids, media_urls = self.process_generated_medias(
                    generated_medias,
                    download_urls=True,
                )
                msg = thread._post_message(
                    subtype_xmlid=subtype_xmlid,
                    body=placeholder_text,
                    author_id=False,
                    attachment_ids=attachment_ids,
                )
                yield {"type": "message_create", "message": msg.message_format()[0]}
                return
        
        return msg

    def process_generated_medias(self, generated_medias, download_urls=False):
        """
        Process a list of media strings (URLs or base64) and return appropriate attachments
        
        Args:
            generated_medias: List of strings (URLs or base64 data)
            download_urls: Whether to download URL content and store as attachments (default: False)
            
        Returns:
            tuple: (attachment_ids, media_urls)
        """
        attachment_ids = []
        media_urls = []
        
        for media in generated_medias:
            if media.startswith(('http://', 'https://')):
                if download_urls:
                    attachment_id = self._create_attachment_from_url(media)
                    if attachment_id:
                        attachment_ids.append(attachment_id)
                    else:
                        media_urls.append(media)
                else:
                    media_urls.append(media)
            else:
                # Assume it's base64 data, create an attachment
                attachment = self.env['ir.attachment'].create({
                    'name': 'Generated Media',
                    'type': 'binary',
                    'datas': media,
                    'res_model': self._name,
                    'res_id': self.id,
                })
                attachment_ids.append(attachment.id)
        
        return attachment_ids, media_urls
        
    def _create_attachment_from_url(self, url):
        """
        Download content from URL and create an attachment
        
        Args:
            url: URL to download content from
            
        Returns:
            int: attachment ID if successful, False otherwise
        """
        try:
            import base64
            import logging
            import os
            from urllib.parse import urlparse

            import requests
            
            _logger = logging.getLogger(__name__)
            
            response = requests.get(url, timeout=10)
            if response.status_code == 200:
                # Try to get filename from URL or use generic name
                filename = os.path.basename(urlparse(url).path)
                
                # Add timestamp to ensure uniqueness
                from datetime import datetime
                timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
                
                # Extract file extension if present
                name_parts = os.path.splitext(filename)
                if name_parts[0]:
                    # If we have a valid filename, add timestamp before extension
                    filename = f"{name_parts[0]}_{timestamp}{name_parts[1]}"
                else:
                    # If no valid filename, use generic name with timestamp
                    filename = f"media_{timestamp}"
                
                # Create attachment with binary data
                attachment = self.env['ir.attachment'].create({
                    'name': filename,
                    'type': 'binary',
                    'datas': base64.b64encode(response.content),
                    'res_model': self._name,
                    'res_id': self.id,
                    'url': url,  # Store original URL for reference
                })
                return attachment.id
            else:
                _logger.warning(f"Failed to download media from URL {url}: HTTP status {response.status_code}")
                return False
        except Exception as e:
            import logging
            _logger = logging.getLogger(__name__)
            _logger.warning(f"Failed to download media from URL {url}: {e}")
            return False