import json
import logging

from odoo import _, api, fields, models
from odoo.exceptions import MissingError, UserError, ValidationError

_logger = logging.getLogger(__name__)


class MailMessage(models.Model):
    _inherit = "mail.message"

    user_vote = fields.Integer(
        string="User Vote",
        default=0,
        help="Vote status given by the user. 0: No vote, 1: Upvoted, -1: Downvoted.",
    )

    def _message_format_fields(self):
        """Extend the list of fields fetched by the base message_format."""
        
        fields_list = ["user_vote", "llm_role", "body_json"]
        return fields_list

    def message_format(self):
        """Override to include custom fields and set proper styling."""
        result = super().message_format()
        llm_fields_to_add = self._message_format_fields()

        for message_data, message in zip(result, self):
            # Manually add the fields as requested to ensure they are in the payload
            for field in llm_fields_to_add:
                if hasattr(message, field):
                    message_data[field] = getattr(message, field)

            if message.llm_role:
                message_data["is_note"] = True

        return result

    def set_user_vote(self, message_id, vote_value):
        """
        Finds a message by ID and sets the user vote, performing validation checks.
        Uses the stored llm_role field for efficient checking.
        """
        message = self.env["mail.message"].browse(message_id)
        if not message.exists():
            raise MissingError(
                _("Message with ID %s not found.") % message_id
            )

        if not isinstance(vote_value, int) or vote_value not in [-1, 0, 1]:
            raise ValidationError(
                _(
                    "Invalid vote value. Must be an integer: 1 (up), -1 (down), or 0 (none)."
                )
            )

        # Use the stored llm_role field for efficient checking
        if message.llm_role in ('assistant', 'tool'):
            message.sudo().write({"user_vote": vote_value})
            return vote_value
        else:
            raise UserError(
                _("Voting is only allowed on messages generated by the assistant")
            )
