"""Tax balance tools: summarize tax amounts by tax"""

import logging
from typing import Optional

from odoo import models

from odoo.addons.llm_tool.decorators import llm_tool

_logger = logging.getLogger(__name__)


class AccountTaxBalance(models.Model):
    _name = "account.tool.tax.balance"
    _inherit = "account.tool.mixin"
    _description = "LLM tools for tax balance reporting"

    @llm_tool(read_only_hint=True, idempotent_hint=True)
    def get_tax_balances(
        self,
        date_from: str,
        date_to: str,
        tax: Optional[str] = None,
        tax_group: Optional[str] = None,
        journal: Optional[str] = None,
        move_type: Optional[str] = None,
        target_move: str = "posted",
    ) -> dict:
        """Get tax balance summary grouped by tax

        Returns base amount and tax amount for each tax in the period.
        Useful for VAT/GST reporting and tax return preparation.

        Args:
            date_from: Period start date (YYYY-MM-DD)
            date_to: Period end date (YYYY-MM-DD)
            tax: Filter by tax name (partial match, optional)
            tax_group: Filter by tax group name (partial match, optional)
            journal: Filter by journal code or name (optional)
            move_type: Filter by move type: "invoice", "bill", etc. (optional)
            target_move: "posted" (default) or "all" entries

        Returns:
            Dictionary with per-tax base and tax amounts
        """
        from .account_move_entry import MOVE_TYPE_MAP

        MoveLine = self.env["account.move.line"]

        # Base domain: lines generated by a tax
        domain = [
            ("tax_line_id", "!=", False),
            ("date", ">=", date_from),
            ("date", "<=", date_to),
        ]

        if target_move == "posted":
            domain.append(("parent_state", "=", "posted"))
        else:
            domain.append(("parent_state", "!=", "cancel"))

        if journal:
            domain.append(("journal_id", "=", self._resolve_journal(journal).id))

        if move_type:
            odoo_type = MOVE_TYPE_MAP.get(move_type, move_type)
            domain.append(("move_id.move_type", "=", odoo_type))

        groups = MoveLine._read_group(
            domain=domain,
            groupby=["tax_line_id"],
            aggregates=["balance:sum", "tax_base_amount:sum"],
        )

        rows = []
        totals = {"base_amount": 0.0, "tax_amount": 0.0}

        for tax_rec, balance_sum, base_sum in groups:
            if not tax_rec:
                continue

            # Apply optional filters
            if tax and tax.lower() not in tax_rec.name.lower():
                continue
            if tax_group and (
                not tax_rec.tax_group_id
                or tax_group.lower() not in tax_rec.tax_group_id.name.lower()
            ):
                continue

            tax_amount = -(balance_sum or 0.0)  # Tax lines are typically credit
            base_amount = base_sum or 0.0

            rows.append(
                {
                    "tax_id": tax_rec.id,
                    "tax_name": tax_rec.name,
                    "tax_group": tax_rec.tax_group_id.name
                    if tax_rec.tax_group_id
                    else "",
                    "type_tax_use": tax_rec.type_tax_use,
                    "base_amount": base_amount,
                    "tax_amount": tax_amount,
                }
            )

            totals["base_amount"] += base_amount
            totals["tax_amount"] += tax_amount

        # Sort by tax name
        rows.sort(key=lambda r: r["tax_name"])

        return {
            "date_from": date_from,
            "date_to": date_to,
            "target_move": target_move,
            "rows": rows,
            "totals": totals,
            "row_count": len(rows),
        }
